version: '3'
services:
  frontend:
    container_name: apache_web
    image: httpd:2-4
    ports:
      -8080:80
    environment:
      - PRUEBA=1234
    depends_on:
      - mysql
      - backend
    networks:
      - net_nginx
      